version: '2'
services:
  weatherapp_backend:
    build:
      context: ./backend/
    command: /usr/app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./backend/:/usr/app
      - /usr/app/node_modules
    ports:
      - "9000:9000"
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  weatherapp_frontend:
    build:
      context: ./frontend/
    command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - weatherapp_backend
    ports:
      - "8000:8000"
